- hosts: all
  tasks:
  - name: stop container
    shell: docker container stop simpleproject-container
  - name: remove container
    shell: docker container rm simpleproject-container
  - name: remove docker image
    shell: docker image rmi dhire/simpleproject
  - name: create container
    shell: docker container run -itd --name simpleproject-container -p 9000:80 dhire/simpleproject
    

     
